---
kind: pipeline
name: development

platform:
  os: linux
  arch: amd64

steps:
- name: vet
  image: golang:1.15
  commands:
  - go version
  - go vet ./...
  environment:
    GO111MODULE: "on"
  volumes:
  - name: gopath
    path: /go

- name: test
  image: golang:1.15
  commands:
  - go version
  - go test -cover ./...
  environment:
    GO111MODULE: "on"
  volumes:
  - name: gopath
    path: /go

volumes:
- name: gopath
  temp: {}

trigger:
  event:
    - push
    - pull_request
  branch:
    - master
    - develop
    - feature/*
    - bugfix/*
    - hotfix/*



---
kind: pipeline
name: staging

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: golang:1.15
  environment:
    CGO_ENABLED: "0"
    GO111MODULE: "on"
    GOOS: linux
  commands:
  - go version
  - "go build -v -ldflags \"-s -w -X main.version=${DRONE_TAG##v}\" -a -tags netgo -o release/linux/amd64/drone-docker ./cmd"
  - du -sh release/linux/amd64/.

- name: executable
  image: golang:1.15
  commands:
  - release/linux/amd64/drone-docker --help

- name: dryrun
  image: joseluisq/drone-docker
  pull: always
  privileged: true
  settings:
    repo: joseluisq/drone-docker
    dockerfile: docker/Dockerfile.linux.amd64
    dry_run: true
    debug: true
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    tags: 1

- name: publish
  image: joseluisq/drone-docker
  pull: always
  privileged: true
  settings:
    repo: joseluisq/drone-docker
    dockerfile: docker/Dockerfile.linux.amd64
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    auto_tag: true
    auto_tag_aliases:
      - latest

trigger:
  ref:
    include:
    - refs/tags/v*
    exclude:
    - refs/tags/**rc**
    - refs/tags/**alpha**
    - refs/tags/**beta**
    - refs/tags/**latest**
    - refs/tags/**dev**

depends_on:
- development



---
kind: pipeline
type: docker
name: notification

platform:
  os: linux
  arch: amd64

steps:
- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: ci-cd

depends_on:
- development
- staging

trigger:
  status:
  - success
  - failure
